mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:root}
  schema: controle_financeiro
  url: ${DATABASE_MYSQL_URL:localhost:3306}

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2