version: '3.7'

services:
  app-financial-control:
    build:
      context: .
      dockerfile: Dockerfile
    image: almirjr94/financial-control
    container_name: financial-control
    ports:
      - "8080:8080"
    environment:
      - DATABASE_MYSQL_USERNAME=root
      - DATABASE_MYSQL_PASSWORD=root
      - DATABASE_MYSQL_URL=mysql
      - API_KEY=aXRhw7o=
    networks:
      - financial-network
    depends_on:
      - mysql

  mysql:
    container_name: mysql_financeiro
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=controle_financeiro
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - financial-network

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    networks:
      - financial-network

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000" # access grafana url
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    networks:
      - financial-network

networks:
  financial-network: