version: '3.7'

services:
  mysql:
    container_name: mysql_financeiro
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=controle_financeiro
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - financeiro_network

networks:
  financeiro_network: