version: '3.7'

services:
  app-financial-control:
    build:
      context: .
      dockerfile: Dockerfile
    image: almirjr94/financial-control
    container_name: financial-control
    ports:
      - "8080:8080"
    environment:
      - DATABASE_MYSQL_USERNAME=root
      - DATABASE_MYSQL_PASSWORD=root
      - DATABASE_MYSQL_URL=mysql
    networks:
      - financial-network
    depends_on:
      - mysql


  mysql:
    container_name: mysql_financeiro
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=controle_financeiro
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - financial-network

networks:
  financial-network: